build:
  image: bjodah/bjodahimg18dev:v1.2
  environment:
    - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-6.0/bin/llvm-symbolizer
    - ASAN_OPTIONS=symbolize=1
  commands:
    - git fetch -tq  # used by ``git describe``
    - (cd tests/; make -B )
    - (cd tests/; make -B EXTRA_COMPILE_ARGS="-DNDEBUG -O3")
    - (cd tests/; make -B CC=clang-6.0 EXTRA_COMPILE_ARGS="-fsanitize=address -O0 -g")
    - (cd tests/; make -B CC=clang-6.0 EXTRA_COMPILE_ARGS="-fsanitize=undefined -O0 -g")
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi
