when:
  - event: [push]

steps:
 - name: build
   image: cont-reg.bjodah.se:443/bjodah/triceratops-3:17
   commands:
    # - git fetch -tq  # used by ``git describe``
    - (cd tests/; make -B )
    - (cd tests/; make -B EXTRA_COMPILE_ARGS="-DNDEBUG -O3")
    - (cd tests/; make -B CC=clang EXTRA_COMPILE_ARGS="-fsanitize=address -O0 -g")
    - (cd tests/; make -B CC=clang EXTRA_COMPILE_ARGS="-fsanitize=undefined -O0 -g")
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi
